Repository jfrog/jenkins-jfrog-plugin, pull requests merged in 2023-03, with the labels that each got.

#32 Don't allow HTTP connections by default
  src/main/java/io/jenkins/plugins/jfrog/configuration/JFrogPlatformBuilder.java
  src/main/resources/io/jenkins/plugins/jfrog/configuration/JFrogPlatformBuilder/global.jelly
  src/main/webapp/help/JFrogPlatformBuilder/help-allowHttpConnections.html
  src/test/java/io/jenkins/plugins/jfrog/configuration/JFrogPlatformBuilderTest.java
Labels: bug, safe to test

#35 Support providing the CLI version
  src/main/java/io/jenkins/plugins/jfrog/ArtifactoryInstaller.java
  src/main/java/io/jenkins/plugins/jfrog/ReleasesInstaller.java
  src/main/resources/io/jenkins/plugins/jfrog/ArtifactoryInstaller/config.jelly
  src/main/resources/io/jenkins/plugins/jfrog/ReleasesInstaller/config.jelly
  src/main/webapp/help/ArtifactoryInstaller/help-repository.html
  src/main/webapp/help/ArtifactoryInstaller/help-serverId.html
  src/main/webapp/help/ArtifactoryInstaller/help-version.html
  src/test/java/io/jenkins/plugins/jfrog/ArtifactoryInstallerCheckCliVersionTest.java
  src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
Labels: improvement

#36 Add support for Jenkins Configuration as Code
  README.md
  pom.xml
  src/main/java/io/jenkins/plugins/jfrog/ArtifactoryInstaller.java
  src/main/java/io/jenkins/plugins/jfrog/JfStep.java
  src/main/java/io/jenkins/plugins/jfrog/configuration/JFrogPlatformBuilder.java
  src/main/java/io/jenkins/plugins/jfrog/configuration/JFrogPlatformInstance.java
  src/main/resources/io/jenkins/plugins/jfrog/ArtifactoryInstaller/config.jelly
  src/main/resources/io/jenkins/plugins/jfrog/configuration/JFrogPlatformBuilder/global.jelly
  src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationITest.java
Labels: new feature

#38 Add Docker example to the README
  README.md
Labels: ignore for release

#42 Support HTTP/S proxy
  pom.xml
  src/main/java/io/jenkins/plugins/jfrog/BinaryInstaller.java
  src/main/java/io/jenkins/plugins/jfrog/CliEnvConfigurator.java
  src/main/java/io/jenkins/plugins/jfrog/JfStep.java
  src/main/java/io/jenkins/plugins/jfrog/Utils.java
  src/test/java/io/jenkins/plugins/jfrog/CliEnvConfiguratorProxyTest.java
  src/test/java/io/jenkins/plugins/jfrog/CliEnvConfiguratorTest.java
Labels: improvement

#44 Allow executing jf from system path
  src/main/java/io/jenkins/plugins/jfrog/JfStep.java
  src/test/java/io/jenkins/plugins/jfrog/JfStepTest.java
Labels: new feature

#48 Support providing arguments as list
  README.md
  images/readme/bash-spaces.png
  src/main/java/io/jenkins/plugins/jfrog/JfStep.java
  src/test/java/io/jenkins/plugins/jfrog/integration/JFrogInstallationITest.java
  src/test/resources/integration/pipelines/basic_commands_array.pipeline
Labels: new feature

#52 Jenkins.instance is missing in remote SSH agent
  src/main/java/io/jenkins/plugins/jfrog/BinaryInstaller.java
Labels: bug

#50 Add missing help buttons
  src/main/resources/io/jenkins/plugins/jfrog/configuration/JFrogPlatformBuilder/global.jelly
  src/main/webapp/help/configuration/JFrogPlatformBuilder/help-artifactoryUrl.html
  src/main/webapp/help/configuration/JFrogPlatformBuilder/help-credentials.html
  src/main/webapp/help/configuration/JFrogPlatformBuilder/help-distributionUrl.html
  src/main/webapp/help/configuration/JFrogPlatformBuilder/help-platformUrl.html
  src/main/webapp/help/configuration/JFrogPlatformBuilder/help-serverId.html
  src/main/webapp/help/configuration/JFrogPlatformBuilder/help-xrayUrl.html
Labels: improvement

#54 Fix JCasC instructions
  README.md
Labels: ignore for release

#55 Fix after serverId was renamed in PR #36
  src/main/resources/io/jenkins/plugins/jfrog/ArtifactoryInstaller/config.jelly
Labels: bug

#56 Fix releases installer
  src/main/java/io/jenkins/plugins/jfrog/ArtifactoryInstaller.java
  src/main/java/io/jenkins/plugins/jfrog/ReleasesInstaller.java
Labels: bug

#57 Automatically encrypt the JFrog CLI config
  src/main/java/io/jenkins/plugins/jfrog/CliEnvConfigurator.java
  src/main/java/io/jenkins/plugins/jfrog/JfStep.java
  src/main/java/io/jenkins/plugins/jfrog/actions/JFrogCliConfigEncryption.java
  src/test/java/io/jenkins/plugins/jfrog/CliEnvConfiguratorTest.java
Labels: improvement

#58 Services URLs are not getting updated
  pom.xml
  src/main/java/io/jenkins/plugins/jfrog/BinaryInstaller.java
  src/main/java/io/jenkins/plugins/jfrog/JfStep.java
  src/main/java/io/jenkins/plugins/jfrog/configuration/JFrogPlatformInstance.java
  src/test/java/io/jenkins/plugins/jfrog/configuration/JFrogPlatformInstanceTest.java
Labels: bug

#61 Slim down plugin
  pom.xml
Labels: improvement
