Repository jfrog/jenkins-jfrog-plugin, pull requests merged in 2023-02, with the labels that each got.

#26 Adding Frogbot to this repository
  .frogbot/frogbot-config.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
Labels: safe to test

#18 Refactor README
  CONTRIBUTING.md
  README.md
Labels: ignore for release, safe to test

#19 Add the Git plugin as a dependency
  pom.xml
Labels: improvement

#28 Fix readme
  README.md
Labels: ignore for release
