Repository jfrog/jenkins-jfrog-plugin, pull requests merged in 2023-08, with the labels that each got.

#75 On MacOSX, os.arch=aarch64 should use arm64 variant of jf
  src/main/java/io/jenkins/plugins/jfrog/OsUtils.java
Labels: bug

#79 Allow for anycase SHA256 HTTP header
  src/main/java/io/jenkins/plugins/jfrog/BinaryInstaller.java
Labels: bug

#82 Update Jenkins version to 2.361.4
  pom.xml
Labels: improvement

#81 Avoid serialization of anonymous classes
  src/main/java/io/jenkins/plugins/jfrog/BinaryInstaller.java
  src/main/java/io/jenkins/plugins/jfrog/Utils.java
  src/main/java/io/jenkins/plugins/jfrog/callables/JFrogCliDownloader.java
  src/main/java/io/jenkins/plugins/jfrog/callables/TempDirCreator.java
Labels: bug

#80 Support no proxy hosts input
  README.md
  src/main/java/io/jenkins/plugins/jfrog/BinaryInstaller.java
  src/main/java/io/jenkins/plugins/jfrog/CliEnvConfigurator.java
  src/main/java/io/jenkins/plugins/jfrog/Utils.java
  src/main/java/io/jenkins/plugins/jfrog/callables/JFrogCliDownloader.java
  src/main/java/io/jenkins/plugins/jfrog/configuration/JenkinsProxyConfiguration.java
  src/test/java/io/jenkins/plugins/jfrog/CliEnvConfiguratorProxyTest.java
  src/test/java/io/jenkins/plugins/jfrog/CliEnvConfiguratorTest.java
  src/test/java/io/jenkins/plugins/jfrog/configuration/JenkinsProxyConfigurationTest.java
Labels: improvement

#73 Update Jenkinsfile syntax
  Jenkinsfile
Labels: ignore for release
