Repository jfrog/jenkins-jfrog-plugin, pull requests merged in 2024-07, with the labels that each got.

#95 Update instructions for creating the remote repo to releases.jfrog.io
  README.md
Labels: ignore for release

#96 Update GitHub Actions workflows
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/tests.yml
Labels: ignore for release

#91 Do not import shaded packages
  src/main/java/io/jenkins/plugins/jfrog/JfStep.java
Labels: improvement

#97 Support No-Proxy hosts with dash
  src/main/java/io/jenkins/plugins/jfrog/configuration/JenkinsProxyConfiguration.java
  src/test/java/io/jenkins/plugins/jfrog/configuration/JenkinsProxyConfigurationTest.java
Labels: bug

#98 Incorrect JCasC configuration for latest JFrog CLI
  src/main/java/io/jenkins/plugins/jfrog/ArtifactoryInstaller.java
  src/main/java/io/jenkins/plugins/jfrog/JfrogInstallation.java
  src/main/java/io/jenkins/plugins/jfrog/ReleasesInstaller.java
  src/test/java/io/jenkins/plugins/jfrog/integration/PipelineTestBase.java
Labels: bug

#100 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: ignore for release
